### ISSUE TITLE
Fails in Safari

### ISSUE THREAD

**Issue by easilyBaffled** [nihey/react-clipboard.js#21]
I have the Clipboard component working perfectly on the Chrome and Firefox browsers, but on Safari it fails quietly. 
I've added `onError={this._handleClipboardError}` to see what was going wrong but there are no details there.

![screen shot 2016-03-14 at 1 57 09 pm](https://cloud.githubusercontent.com/assets/4247680/13759840/54572822-e9ed-11e5-96cc-92b3a9fbaa61.png)

**Comment by nihey** [comment]
Its seems `clipboard.js`, the main dependency of `react-clipboard.js` does not support Safari (browser support info [here](https://github.com/zenorocha/clipboard.js#browser-support))

**Comment by andymac4182** [comment]
It appears to be supported in Safari 10+ now.

**Comment by nihey** [comment]
Alright, I think it can be closed now, thanks for the input @andymac4182
