### ISSUE TITLE
Allow option to instantiate clipboard.js by passing in HTMLElement rather than the selector String.

### ISSUE THREAD

**Issue by jseminck** [nihey/react-clipboard.js#22]
Clipboard.js supports an option now where we can pass in an HTMLElement in the constructor, see:

https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-node.html#L16-L19

This is useful, because in some situations we want to stopPropagation on the copy link, but in the current way of doing this it results that the event is not propagated to the clipboard.js package. 

There are several issues on clipboard.js github page regarding stopPropagation, where the author suggest to use this approach:
- https://github.com/zenorocha/clipboard.js/issues/138
- https://github.com/zenorocha/clipboard.js/issues/91

I have tested with this component, and instantiating Clipboard by passing the DOMNode fixes my problem:
```js
        this.clipboard = new Clipboard(ReactDOM.findDOMNode(this), options);
```

*Edit-2*: A better way seems to be to use this.refs instead. This also works fine. See my fork as an experiment.

However, would be nice if the component was updated with a property to use string instantiation or HTMLElement instantiation.

*Edit-1*: Perhaps this should even be the official implementation? The old clipboard.js API that takes a selector was pretty weird and this plugin is also doing all sorts of magic to work around that, by using a counter and creating a custom id ...

**Comment by nihey** [comment]
> Perhaps this should even be the official implementation? The old clipboard.js API that takes a selector was pretty weird and this plugin is also doing all sorts of magic to work around that, by using a counter and creating a custom id ...

You're right, using a counter to create that synthetic `id` was a pretty hacky solution, but I was the best thing to do at that time.

> This is useful, because in some situations we want to stopPropagation on the copy link, but in the current way of doing this it results that the event is not propagated to the clipboard.js package. 

No doubt about that, using the way that will deliver less problems and provides more features is the best thing to do.

@jseminck That is a very nice contribution, would you be willing to submit a pull request from your repository? Giving a first look at it, I saw nothing wrong. But I'll review it thoroughly as soon as I get home tonight.

**Comment by jseminck** [comment]
I'll make the PR. I tested the change in my project and everything works fine, but I haven't tested with any of the other examples yet.

**Comment by nihey** [comment]
Fixed by https://github.com/nihey/react-clipboard.js/pull/23

**Comment by jseminck** [comment]
Tested just now with 0.2.0 and everything is working!

Thanks for the quick response.
