### ISSUE TITLE
Version 0.2.0 doesn't work on React 0.13

### ISSUE THREAD

**Issue by ewiner** [nihey/react-clipboard.js#24]
Looks like the library was recently changed to use `refs.element`.  In React 0.13, you'd need to call `refs.element.getDOMNode()`.  I think it's fine to not support old React versions, but you should probably update the `peerDependencies` in `package.json` accordingly.

**Comment by nihey** [comment]
You're right, I'll do a minor release today that should be able to support 0.13.

Thanks for reporting.
