### ISSUE TITLE
release 1.0.0 and follow semver

### ISSUE THREAD

**Issue by haoxins** [nihey/react-clipboard.js#30]
can we release this module as `1.0.0` and follow `semver`? cc @nihey 

😄

**Comment by nihey** [comment]
@haoxins Sure :)

Thanks for the contributions!! (https://github.com/nihey/react-clipboard.js/pull/32, https://github.com/nihey/react-clipboard.js/pull/31)
I'll look into them as soon as possible, merge them and release `1.0.0`

**Comment by haoxins** [comment]
thanks 😄

**Comment by haoxins** [comment]
any update？


发自我的 iPhone

**Comment by nihey** [comment]
Sorry for the delay, I'll be releasing 1.0.0 soon :)
