### ISSUE TITLE
'style' prop should be object

### ISSUE THREAD

**Issue by hashwin** [nihey/react-clipboard.js#34]
Hi,

I've set this up in my project and it works well.
But I am getting some warnings that don't seem right.
```
Warning: Failed prop type: Invalid prop `style` of type `object` supplied to `ClipboardButton`, expected `string`.
```
Aren't inline styles usually objects?
```
Warning: Failed prop type: Invalid prop `children` supplied to `ClipboardButton`.
```
Not sure why we would have to explicitly allow children, maybe something is disallowing it?

**Comment by nihey** [comment]
> Aren't inline styles usually objects?

You're right, inline styles are always objects, no reason to keep them as strings. I'll fix that as soon as I get home.

> Not sure why we would have to explicitly allow children, maybe something is disallowing it?

This was a recently sent pull request, I can test the default behavior of that and remove it if it's not necessary.

Thanks for the input.
