### ISSUE TITLE
ES6 Classes example

### ISSUE THREAD

**Issue by bondz** [nihey/react-clipboard.js#36]
Can the examples be updated to use ES6 classes like [this](http://www.webpackbin.com/VJR5pUcIf)?

**Comment by nihey** [comment]
Sure! Maybe I should've done them like this from the beginning.

By the end of today it shall be done.

**Comment by bondz** [comment]
@nihey can you take a look at the `CustomComponent` example in the bin, we should be able to get the clipboard rendered like that.

**Comment by nihey** [comment]
> @nihey, awesome. I could send a PR too.

@bondz Nice, if you want and have the time, PRs are always welcome :+1: 

I haven't used `styled-components` very much, but another example of it would surely be good.

**Comment by bondz** [comment]
@nihey it could be any component really, `styled-components` are just ordinary components with styles, as of now, at [index.js#L9](https://github.com/nihey/react-clipboard.js/blob/master/index.js#L9) only strings are allowed.

**Comment by nihey** [comment]
> Would work on a PR.

@bondz Alright, I'll be waiting, thanks for contributing!

**Comment by nihey** [comment]
Fixed in https://github.com/nihey/react-clipboard.js/commit/8c1c380b4b9590bf63c861c7cc9c00c8c62cb464
