### ISSUE TITLE
React Element as Component

### ISSUE THREAD

**Issue by bondz** [nihey/react-clipboard.js#38]
The components currently renders a button by default or lets the user specify a HTML tag as string to render.

This can be expanded to allow the component accept a React Element as the component to render. For example.

```jsx
<ClipboardButton component={MyReactElement} data-clipboard-text="Hello World" />
```

This would require that the component only renders a button and passes all props along to the component. I'm might cause breaking changes.

This is an example I'm hoping to achieve
```jsx
<ClipboardButton component={MyCustomElement} customElementProp="string" disabled />
```

As of now, only specific props are passed to the component, and the button's attributes must be prefixed with `button-`

This would require some changes and better tests.
My initial take on this is [here](https://github.com/bondz/react-clipboard.js/tree/Custom-Components)

-----
- [ ]  Allow React Element to be passed as prop
- [ ]  Remove the need for `button-*` props
- [ ]  `option-*` props should be passed as objects object
- [ ]  Better tests
- [ ]  Document API

**Comment by nihey** [comment]
> This would require that the component only renders a button and passes all props along to the component. I'm might cause breaking changes.

I've undestood, and seeing [your changes](https://github.com/bondz/react-clipboard.js/tree/Custom-Components) it most likely will. But don't bother yourself in making it backwards compatible, I can deal with that later too.

>  Better tests

It would surely be a great contribution, and with some test infrastructure I'll be able to work on top of that to make sure the component is backwards compatible (and still does not break for the latest API).

> As of now, only specific props are passed to the component, and the button's attributes must be prefixed with `button-`

I've undestood the issue and believe you are right.

Thanks again for your input @bondz

**Comment by bondz** [comment]
Great. I'll being work on cleaning up the branch and submit it as a PR.

**Comment by Sunshine168** [comment]
hello any news of this feat?

**Comment by nihey** [comment]
@Sunshine168 This was implemented, but this issue was no properly closed, thanks for remembering: I just need to add it to the documentation. https://github.com/nihey/react-clipboard.js/blob/master/index.js#L98

You can use this feature exactly as stated:

```
<ClipboardButton component={MyReactElement} data-clipboard-text="Hello World" />
```

**Comment by briefguo** [comment]
> @Sunshine168 This was implemented, but this issue was no properly closed, thanks for remembering: I just need to add it to the documentation. https://github.com/nihey/react-clipboard.js/blob/master/index.js#L98
> 
> You can use this feature exactly as stated:
> 
> ```
> <ClipboardButton component={MyReactElement} data-clipboard-text="Hello World" />
> ```

Something about  prop-types need to upgrade as well,  otherwise

```
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `ClipboardButton`, expected `string`.
    in ClipboardButton (created by UrlShortener)
    in UrlShortener (created by SunmiEngine)
    in Container (created by SunmiEngine)
    in SunmiEngine
```
