### ISSUE TITLE
Bump clipboard.js dependency for newer node versions

### ISSUE THREAD

**Issue by wingrunr21** [nihey/react-clipboard.js#40]
The version of `delegate` used by the specified version of `clipboard.js` throws an error in recent versions of node (see zenorocha/delegate#10). `clipboard.js` and its dependencies have been updated to compensate. Could you bump the version here as well?

**Comment by nihey** [comment]
Sure, will do as soon as I get home today.

Thanks!

**Comment by wingrunr21** [comment]
@nihey pinging on this. would a PR be preferable?

**Comment by nihey** [comment]
@wingrunr21 It surely would, It would save some time in releasing a new version of it. Sorry for the delay on this, I've been dealing with a lot of personal changes over the last month.

**Comment by wingrunr21** [comment]
No worries. I'll see if it's an easy upgrade and hopefully take a look tonight
