### ISSUE TITLE
Use Webpack 3 for building

### ISSUE THREAD

**Issue by nihey** [nihey/react-clipboard.js#42]

**Comment by marcinlichwala** [comment]
Hello @nihey, I would gladly take this one :)

**Comment by nihey** [comment]
Hi @marcinlichwala ,

> maybe we should change this issue to update to webpack 3

Sure! Go ahead!

**Comment by marcinlichwala** [comment]
Hey @nihey.
I've just created this PR:
https://github.com/nihey/react-clipboard.js/pull/46

Please take a look :)

**Comment by nihey** [comment]
Fixed by https://github.com/nihey/react-clipboard.js/pull/46
