### ISSUE TITLE
option-text propType validation?

### ISSUE THREAD

**Issue by bambielli** [nihey/react-clipboard.js#51]
Hello,

Thanks for making react-clipboard.js!

I ran into a problem the other day in a project that uses react-clipboard. We are using the `option-text` `onSuccess` pattern for copying and alerting to the user that a copy occurred.

We inadvertently passed a string as our `option-text` prop instead of a function that returns a string. This caused the copy functionality to break. 

Would it be possible to add additional prop validation for common option props like option-text?

After looking at the code, I realize this might be a bit more challenging than I had originally expected, since it seems that all of the option-* params are dynamic.

**Comment by nihey** [comment]
Hi Brian,

Thanks for the feedback, although it could be a bit challenging, I'll try to address it on this weekend! I'll keep you updated.

Best,

**Comment by bambielli** [comment]
Actually maybe it's not so hard! 

https://github.com/nihey/react-clipboard.js/blob/27644c5b09ce19a5c4f79945410954956f4cb5ef/index.js#L6

Would it be possible to just define a more complicated PropTypes object for `options` on this line? That doesn't seem too bad.

**Comment by nihey** [comment]
[Apparently there is](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes), it seems like I can use a function to validate custom props, I'll give it a try and should be able to come up with a solution for it.
