### ISSUE TITLE
2.0.0: Error: Cannot find module './clipboard-action'

### ISSUE THREAD

**Issue by ibc** [nihey/react-clipboard.js#52]
I upgraded react-clipboard.js from 1.1.3 to 2.0.0. When running browserify on my project now I get this error:

```
Error: Cannot find module './clipboard-action' from '/XXXXX/node_modules/clipboard/dist'
```

Indeed, `node_modules/clipboard/dist` just contains this:

```
clipboard.js
clipboard.min.js
```

**Comment by nihey** [comment]
@ibc In order to import `clipboard-action`, I believe you would need to use `clipboard` dependency, which [contains it](https://github.com/zenorocha/clipboard.js/search?q=clipboard-action&unscoped_q=clipboard-action).
