### ISSUE TITLE
Looks like the Clipboard name changed to ClipboardJS

### ISSUE THREAD

**Issue by veeramarni** [nihey/react-clipboard.js#54]
In the following code, it need to be changed to `ClipboardJS` as it was changed in [here](https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.0)

https://github.com/nihey/react-clipboard.js/blob/53d1167ec476992304d4f767f79ec6b86d206f2f/webpack.config.js#L21

Due to it I'm getting following error. Unfortunately, this error won't be seen until we bundle with latest webpack `(4.19.0)` otherwise we don't see it in previous version of webpack. 

![image](https://user-images.githubusercontent.com/3382355/45597135-7c365000-b995-11e8-81ec-4e0028503127.png)

**Comment by nihey** [comment]
@veeramarni Thanks for the changed, I believe that with your PR (https://github.com/nihey/react-clipboard.js/pull/55) this issue should be solved. I will publish it soon.
