### ISSUE TITLE
Add typescript definition

### ISSUE THREAD

**Issue by pierreTklein** [nihey/react-clipboard.js#59]
Hi,

I was hoping to use this with my Typescript project, but I noticed that `@types/react-clipboard.js` doesn't exist. Having a type definition would be super useful!

**Comment by nihey** [comment]
Hi @pierreTklein 

I understand the issue, but I'm not very proficient in `TypeScript` and I'm in a bit of a lack of time lately, would be interested in contributing to add a `@types/react-clipboard.js` file to this repo? I would gladly receive a Pull Request for this.

**Comment by briefguo** [comment]
Hi @nihey 

#60

**Comment by nihey** [comment]
@briefguo,

Thanks for the Pull Request, I should deploy it by this Sunday!
