### ISSUE TITLE
Module not found: Error: Can't resolve 'react-clipboard.js'

### ISSUE THREAD

**Issue by dzienisz** [nihey/react-clipboard.js#61]
![zrzut ekranu 2019-02-7 o 16 12 41](https://user-images.githubusercontent.com/3521624/52420896-3cface00-2af3-11e9-979a-38102cbbfabf.png)

Hey I can't build my app. Do you know what's wrong?

**Comment by nartydev** [comment]
What is the fix ?

**Comment by dzienisz** [comment]
I think I was problem with npm. I apologize for not providing the solution back then.

**Comment by nartydev** [comment]
Ah yes, i have found, i have forgotten to add in the package.json
