### ISSUE TITLE
Usage in modal

### ISSUE THREAD

**Issue by JeSuis** [nihey/react-clipboard.js#68]
I'm having the usual problem of this not working in a modal.
I tried the recommended solution of `option-container` as noted in the advanced usage, but can't get that to work.

https://clipboardjs.com/#advanced-usage

I'm specially using material ui rather the the bootstrap modal but it should be the same fix.

**Comment by JeSuis** [comment]
I resolved this, if you're using Material UI, you need to use PaperProps and set the ID on that and not the Dialogue

**Comment by JeSuis** [comment]
Note the main problem here seems to be with not being able to get the element when needed unless you want to wrap it in a setTimeout which is ugly

**Comment by nihey** [comment]
@JeSuis could you provide a code snippet example for this problem? We can try to work on a solution based on that.

**Comment by git-ekuo** [comment]
@nihey , I believe this can be closed. 

I am also using Modal in material-ui. https://clipboardjs.com/#advanced-usage suggests us to pass the node element of the `Modal` container to `option-container`. However, modal is not always available, thus @JeSuis 's suggestion to create the component inside `setTimeout`. The way I resolved this was by ensuring the `Modal` container is created and ready before I create the `react-clipboard.js` component. Hope this helps.
