### ISSUE TITLE
SSR: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by garthenweb** [nihey/react-clipboard.js#69]
I get an error on server side rendering after updating from v2.0.3 to v2.0.5:

```
/.../node_modules/react-clipboard.js/dist/react-clipboard.js:10
})(window, function(__WEBPACK_EXTERNAL_MODULE_clipboard__, __WEBPACK_EXTERNAL_MODULE_prop_types__, __WEBPACK_EXTERNAL_MODULE_react__) {
   ^
ReferenceError: window is not defined
    at Object.<anonymous> (/.../node_modules/react-clipboard.js/dist/react-clipboard.js:10:4)
```

Using NodeJS v10.14.2

**Comment by paintedbicycle** [comment]
Running into this with next.js

**Comment by nihey** [comment]
@garthenweb Thanks for reporting, I'll investigate it this week. It may be related to the new webpack config.

**Comment by nihey** [comment]
@garthenweb @paintedbicycle , Could you try it on `2.0.6` to see if this is resolved? I've made some changes on `webpack` config that should solve the issue. If it is not fixed, you can re-open it here!

**Comment by garthenweb** [comment]
Works like a charm for me, thank you for the fast fix!
