### ISSUE TITLE
Something related to custom components is messed up

### ISSUE THREAD

**Issue by uyouthe** [nihey/react-clipboard.js#74]
When supplying custom component as a `component` prop, there are some errors:
```
Warning: Failed prop type: Invalid prop `component` supplied to `ClipboardButton`, expected a ReactNode.
Warning: Failed prop type: Invalid prop `children` supplied to `ClipboardButton`.
```

My code:
```
import Clipboard from 'react-clipboard.js'
import Button from 'ui/button'

...

<Clipboard component={ Button }>
   { this.props.children }
</Clipboard>
```

**Comment by nihey** [comment]
@uyouthe I'm investigating the issue, it seems that is related to not using `react-dom` when extracting the DOM Node of the custom component. I've did a little refactor and should fix it soon.

Just a reminder too in case this happen again: Stateless/Functional components are not yet supported as custom components. Wrapping it in a Stateful/Class should work just fine after `2.0.10`

**Comment by uyouthe** [comment]
@nihey maybe make an auto-wrapping to stateful component as far as statefulness there doesn't serve any purpose other than satisfying React?

**Comment by nihey** [comment]
@uyouthe That's an excellent idea, I'll register it as an issue to be developed soon.
