### ISSUE TITLE
BC break in 2.0.10

### ISSUE THREAD

**Issue by ujovlado** [nihey/react-clipboard.js#77]
https://github.com/nihey/react-clipboard.js/blob/3f40a8ae59b8efe4b71c031dc58b433f8a2380ab/index.js#L6

Create ref is available since react 16.3:

https://reactjs.org/docs/refs-and-the-dom.html

**Comment by nihey** [comment]
That's a good observation, I'll replace the current code with a more backwards compatible one, release, then do another release with these `16.3` refactor (or maybe a straight `16.8` hook refactor).
